# Generated by Django 4.2.3 on 2023-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
