# Generated by Django 4.2.3 on 2023-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
