# Generated by Django 4.2.3 on 2023-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_notification_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
