# Generated by Django 4.2.3 on 2023-09-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_remove_notification_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='star',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='film.film'),
        ),
    ]
